gelato_homepage:
    path:     /
    defaults: { _controller: GelatoBundle:Default:index }

gelato_filtro_provincia:
    path:     /filtro_provincia/{id}
    defaults: { _controller: GelatoBundle:Default:filtroProvincie }

gelato_filtro_citta:
    path:     /filtro_citta/{id}
    defaults: { _controller: GelatoBundle:Default:filtroCitta }

gelato_filtro_cerca_provincia:
    path:     /filtro_cerca_provincia/{id}
    defaults: { _controller: GelatoBundle:Default:filtroCercaProvincie }

gelato_filtro_cerca_citta:
    path:     /filtro_cerca_citta/{id}
    defaults: { _controller: GelatoBundle:Default:filtroCercaCitta }    

gelato_profilo_utente:
    path:     /utente
    defaults: { _controller: GelatoBundle:Default:utente }

gelato_profilo_amministratore:
    path:     /amministratore
    defaults: { _controller: GelatoBundle:Default:amministratore }

gelato_contatti:
    path:     /contatti
    defaults: { _controller: GelatoBundle:Default:contatti }

gelato_risultati:
    path:     /risultati
    defaults: { _controller: GelatoBundle:Default:risultati }

gelato_risultatiroot:
    path:     /risultatiroot
    defaults: { _controller: GelatoBundle:Default:risultatiroot }

gelato_registrazione:
    path:     /registrazione
    defaults: { _controller: GelatoBundle:Default:registrazione }

