gelato_homepage:
    path:     /
    defaults: { _controller: GelatoBundle:Default:index }

hpprovincefilter:
    path:     /hpprovincefilter/{id}
    defaults: { _controller: FrontEndBundle:Default:hpProvinceFilter }

hpcityfilter:
    path:     /hpcityfilter/{id}
    defaults: { _controller: FrontEndBundle:Default:hpCityFilter }

searchprovincefilter:
    path:     /searchprovincefilter/{id}
    defaults: { _controller: FrontEndBundle:Default:searchProvinceFilter }

searchcityfilter:
    path:     /searchcityfilter/{id}
    defaults: { _controller: FrontEndBundle:Default:searchCityFilter }    

gelato_profilo_utente:
    path:     /utente
    defaults: { _controller: GelatoBundle:Default:utente }

gelato_profilo_amministratore:
    path:     /amministratore
    defaults: { _controller: GelatoBundle:Default:amministratore }

gelato_contatti:
    path:     /contatti
    defaults: { _controller: GelatoBundle:Default:contatti }

gelato_risultati:
    path:     /risultati
    defaults: { _controller: GelatoBundle:Default:risultati }

gelato_risultatiroot:
    path:     /risultatiroot
    defaults: { _controller: GelatoBundle:Default:risultatiroot }

gelato_registrazione:
    path:     /registrazione
    defaults: { _controller: GelatoBundle:Default:registrazione }

