<?php

namespace GelatoBundle\Repository;

/**
 * GelateriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GelateriaRepository extends \Doctrine\ORM\EntityRepository
{
}
