<?php

namespace GelatoBundle\Repository;

/**
 * GustoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GustoRepository extends \Doctrine\ORM\EntityRepository
{
}
