<?php

namespace GelatoBundle\Repository;

/**
 * GustiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GustiRepository extends \Doctrine\ORM\EntityRepository
{
}
