<?php

namespace GelatoBundle\Repository;

/**
 * RicercaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RicercaRepository extends \Doctrine\ORM\EntityRepository
{
}
